-- Phase 4 auth/user ownership patch.
-- Run this whole file in Supabase SQL Editor after the base schema exists.
-- It uses only complete statements so it is safe to copy/paste as a standalone migration.

create table if not exists public.invoice_items (like public.customers including all);

alter table public.customers add column if not exists user_id uuid null;
alter table public.estimates add column if not exists user_id uuid null;
alter table public.estimate_items add column if not exists user_id uuid null;
alter table public.jobs add column if not exists user_id uuid null;
alter table public.job_items add column if not exists user_id uuid null;
alter table public.tasks add column if not exists user_id uuid null;
alter table public.expenses add column if not exists user_id uuid null;
alter table public.invoices add column if not exists user_id uuid null;
alter table public.invoice_items add column if not exists user_id uuid null;
alter table public.payments add column if not exists user_id uuid null;
alter table public.time_entries add column if not exists user_id uuid null;
alter table public.shopping_lists add column if not exists user_id uuid null;
alter table public.shopping_list_items add column if not exists user_id uuid null;
alter table public.material_orders add column if not exists user_id uuid null;
alter table public.material_order_items add column if not exists user_id uuid null;
alter table public.suppliers add column if not exists user_id uuid null;
alter table public.allowances add column if not exists user_id uuid null;
alter table public.allowance_selections add column if not exists user_id uuid null;
alter table public.workers add column if not exists user_id uuid null;
alter table public.receipts add column if not exists user_id uuid null;
alter table public.job_photos add column if not exists user_id uuid null;
alter table public.notes add column if not exists user_id uuid null;
alter table public.activity_log add column if not exists user_id uuid null;

alter table public.invoice_items add column if not exists invoice_id text;
alter table public.invoice_items add column if not exists quantity numeric;
alter table public.invoice_items add column if not exists unit text;
alter table public.invoice_items add column if not exists unit_price numeric;
alter table public.invoice_items add column if not exists total numeric;
alter table public.invoice_items add column if not exists source_type text;
alter table public.invoice_items add column if not exists source_id text;

create index if not exists invoice_items_invoice_id_idx on public.invoice_items (invoice_id);

alter table public.customers enable row level security;
alter table public.estimates enable row level security;
alter table public.estimate_items enable row level security;
alter table public.jobs enable row level security;
alter table public.job_items enable row level security;
alter table public.tasks enable row level security;
alter table public.expenses enable row level security;
alter table public.invoices enable row level security;
alter table public.invoice_items enable row level security;
alter table public.payments enable row level security;
alter table public.time_entries enable row level security;
alter table public.shopping_lists enable row level security;
alter table public.shopping_list_items enable row level security;
alter table public.material_orders enable row level security;
alter table public.material_order_items enable row level security;
alter table public.suppliers enable row level security;
alter table public.allowances enable row level security;
alter table public.allowance_selections enable row level security;
alter table public.workers enable row level security;
alter table public.receipts enable row level security;
alter table public.job_photos enable row level security;
alter table public.notes enable row level security;
alter table public.activity_log enable row level security;

drop policy if exists "Users manage own rows" on public.customers;
create policy "Users manage own rows" on public.customers for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.estimates;
create policy "Users manage own rows" on public.estimates for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.estimate_items;
create policy "Users manage own rows" on public.estimate_items for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.jobs;
create policy "Users manage own rows" on public.jobs for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.job_items;
create policy "Users manage own rows" on public.job_items for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.tasks;
create policy "Users manage own rows" on public.tasks for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.expenses;
create policy "Users manage own rows" on public.expenses for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.invoices;
create policy "Users manage own rows" on public.invoices for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.invoice_items;
create policy "Users manage own rows" on public.invoice_items for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.payments;
create policy "Users manage own rows" on public.payments for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.time_entries;
create policy "Users manage own rows" on public.time_entries for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.shopping_lists;
create policy "Users manage own rows" on public.shopping_lists for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.shopping_list_items;
create policy "Users manage own rows" on public.shopping_list_items for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.material_orders;
create policy "Users manage own rows" on public.material_orders for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.material_order_items;
create policy "Users manage own rows" on public.material_order_items for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.suppliers;
create policy "Users manage own rows" on public.suppliers for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.allowances;
create policy "Users manage own rows" on public.allowances for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.allowance_selections;
create policy "Users manage own rows" on public.allowance_selections for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.workers;
create policy "Users manage own rows" on public.workers for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.receipts;
create policy "Users manage own rows" on public.receipts for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.job_photos;
create policy "Users manage own rows" on public.job_photos for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.notes;
create policy "Users manage own rows" on public.notes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "Users manage own rows" on public.activity_log;
create policy "Users manage own rows" on public.activity_log for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
