export const TABLES = {
  customers: 'customers',
  estimates: 'estimates',
  estimateItems: 'estimate_items',
  jobs: 'jobs',
  jobItems: 'job_items',
  tasks: 'tasks',
  expenses: 'expenses',
  invoices: 'invoices',
  payments: 'payments',
  timeEntries: 'time_entries',
  shoppingLists: 'shopping_lists',
  shoppingListItems: 'shopping_list_items',
  materialOrders: 'material_orders',
  materialOrderItems: 'material_order_items',
  suppliers: 'suppliers',
  allowances: 'allowances',
  allowanceSelections: 'allowance_selections',
  workers: 'workers',
  receipts: 'receipts',
  jobPhotos: 'job_photos',
  notes: 'notes',
  activityLog: 'activity_log',
} as const;
