import type { BrandingSettings } from '../data/types';

export type EmailTemplateType = 'estimate' | 'invoice' | 'changeorder' | 'expense';

type TemplateData = {
  branding: BrandingSettings;
  subject?: string;
  estimate?: any;
  invoice?: any;
  changeOrder?: any;
  customer?: any;
  totals?: any;
};

function headerHTML(branding: BrandingSettings) {
  const logo = branding.logoDataUrl || branding.logoUrl || '';
  const logoTag = logo ? `<img src="${logo}" alt="logo" style="height:34px; object-fit:contain; vertical-align:middle;" />` : '';
  return `
  <div style="background:${branding.primaryColor || '#1f3a8a'}; color:white; padding:12px 16px; display:flex; align-items:center; gap:12px; font-family:${branding.fontFamily};">
    <span style="font-weight:600; font-size:18px;">${branding.brandName || 'Brand'}</span>
    <span style="margin-left:auto; vertical-align:middle;">${logoTag}</span>
  </div>
  `;
}

export function renderEmailHTML(type: EmailTemplateType, branding: BrandingSettings, data: any): { subject: string; html: string } {
  const subject = (() => {
    if (type === 'estimate' && data?.estimate?.name) return `Estimate: ${data.estimate.name}`;
    if (type === 'invoice' && data?.invoice?.invoiceNumber) return `Invoice: ${data.invoice.invoiceNumber}`;
    if (type === 'changeorder' && data?.changeOrder?.id) return `Change Order: ${data.changeOrder.id}`;
    if (type === 'expense') return `Expense Receipt`;
    return 'Document';
  })();

  const bodyParts = [] as string[];
  bodyParts.push(`<p style="font-family:${branding.fontFamily || 'Arial'}, sans-serif; font-size:14px; color:#333;">Hello${data?.customer?.name ? ' ' + data.customer.name : ''},</p>`);
  // Simple content per type
  if (type === 'estimate' && data?.estimate) {
    bodyParts.push(`<p style="font-family:${branding.fontFamily || 'Arial'}, sans-serif; font-size:14px;">Please review your estimate: <strong>${data.estimate.name}</strong></p>`);
    bodyParts.push(`<p style="font-family:${branding.fontFamily || 'Arial'}, sans-serif; font-size:14px;">Total: <strong>${data.totals?.total ?? ''}</strong></p>`);
  } else if (type === 'invoice' && data?.invoice) {
    bodyParts.push(`<p style="font-family:${branding.fontFamily || 'Arial'}, sans-serif; font-size:14px;">Invoice amount: <strong>${data.invoice.amount}</strong></p>`);
  } else if (type === 'changeorder' && data?.changeOrder) {
    bodyParts.push(`<p style="font-family:${branding.fontFamily || 'Arial'}, sans-serif; font-size:14px;">Change Order: ${data.changeOrder.description}</p>`);
  } else {
    bodyParts.push(`<p style="font-family:${branding.fontFamily || 'Arial'}, sans-serif; font-size:14px;">Please review the document.</p>`);
  }
  bodyParts.push(`<p style="font-family:${branding.fontFamily || 'Arial'}, sans-serif; font-size:12px; color:#666;">This email was generated by ${branding.brandName}.</p>`);

  const html = `<!doctype html><html><body style="margin:0; padding:0; font-family:${branding.fontFamily || 'Arial'}, sans-serif; background:#f6f7fb;">${headerHTML(branding)}<div class="container" style="padding:20px; background:white; max-width:800px; margin:20px auto; border-radius:8px; box-shadow:0 2px 8px rgba(0,0,0,.05);">${bodyParts.join('')}${''}</div></body></html>`;
  return { subject, html };
}

export function renderEmailAll(type: EmailTemplateType, branding: BrandingSettings, data: any): { subject: string; html: string; text: string } {
  const { subject, html } = renderEmailHTML(type, branding, data);
  // Simple plaintext fallback derived from the type and data
  let text = '';
  const name = data?.customer?.name || '';
  if (type === 'estimate') {
    const estName = data?.estimate?.name ?? '';
    const total = (typeof data?.totals?.total === 'number') ? data.totals.total : '';
    text = `Hello ${name},\n\nPlease review the estimate: ${estName}. Total: ${total}.\n\nThank you, ${branding.brandName}`;
  } else if (type === 'invoice') {
    const inv = data?.invoice ?? {};
    text = `Hello ${name},\n\nPlease review Invoice ${inv.invoiceNumber ?? ''}: ${inv.amount ?? ''}.\n\nThank you, ${branding.brandName}`;
  } else if (type === 'changeorder') {
    const c = data?.changeOrder ?? {};
    text = `Hello ${name},\n\nChange Order: ${c.description ?? ''}.\n\nThank you, ${branding.brandName}`;
  } else {
    text = `Hello ${name},\n\nPlease review the document.\n\nThank you, ${branding.brandName}`;
  }
  return { subject, html, text };
}
